language: node_js
node_js:
  - "8"
before_script:
  - npm install -g gulp-cli elm
script:
  - gulp pug
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: ryannhg/ryannhg.github.io
  target_branch: master
  local_dir: _docs
  on:
    branch: master
