language: node_js
node_js:
  - "8"
before_script:
  - npm install -g gulp-cli elm
script:
  - gulp
  - rm .gitignore
  - rm -rf node_modules/
  - rm -rf elm-stuff/
  - rm -rf src/
  - rm -rf assets/
  - rm -rf posts/
  - rm -rf *.json
  - rm -rf *.pug
  - rm -rf *.js
  - cp -r _docs/* .
  - rm -rf _docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: ryannhg.github.io
  target_branch: master
  on:
    branch: master
